# Generated by Django 4.2.7 on 2025-11-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField()),
                ("homepage", models.URLField(blank=True, null=True)),
                ("stars_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("watchers_count", models.IntegerField(default=0)),
                ("open_issues_count", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0, help_text="Size in KB")),
                (
                    "primary_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("topics", models.JSONField(blank=True, default=list)),
                ("is_fork", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "custom_description",
                    models.TextField(
                        blank=True, help_text="Override GitHub description"
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "ordering": ["-featured", "display_order", "-stars_count"],
            },
        ),
        migrations.CreateModel(
            name="GitHubLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("bytes_count", models.IntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="github_integration.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-bytes_count"],
            },
        ),
        migrations.CreateModel(
            name="GitHubCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField()),
                ("author_name", models.CharField(max_length=200)),
                ("author_email", models.EmailField(max_length=254)),
                ("committed_at", models.DateTimeField()),
                ("url", models.URLField()),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github_integration.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-committed_at"],
            },
        ),
    ]
