# Generated by Django 4.2.7 on 2025-11-01 20:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Main blog content with support for images, videos, GIFs, code, and more"
            ),
        ),
    ]
