"""
Management command to set up Industry Index with OpenAI API key and generate initial rankings
"""
from django.core.management.base import BaseCommand
from portfolio.models import IndustryIndexSettings
from portfolio.industry_analyzer import update_industry_rankings
from decouple import config


class Command(BaseCommand):
    help = 'Set up Industry Index with OpenAI API key and generate initial rankings'

    def add_arguments(self, parser):
        parser.add_argument(
            '--api-key',
            type=str,
            help='OpenAI API key',
        )

    def handle(self, *args, **options):
        api_key = options.get('api_key')
        
        if not api_key:
            api_key = config('OPENAI_API_KEY', default='')
        
        self.stdout.write('Setting up Industry Index...')
        
        # Get or create settings
        settings, created = IndustryIndexSettings.objects.get_or_create(
            pk=1,
            defaults={
                'page_description': 'This ranking is generated by AI analyzing my skills, research interests, blog posts, education, and professional activities. The index updates regularly to reflect my evolving expertise and interests.',
                'openai_api_key': api_key
            }
        )
        
        if not created:
            settings.openai_api_key = api_key
            settings.save()
            self.stdout.write(self.style.SUCCESS('✓ Updated OpenAI API key'))
        else:
            self.stdout.write(self.style.SUCCESS('✓ Created Industry Index settings'))
        
        # Generate initial rankings
        self.stdout.write('Generating industry rankings with AI...')
        self.stdout.write('This may take 10-30 seconds...')
        
        success = update_industry_rankings(api_key)
        
        if success:
            self.stdout.write(self.style.SUCCESS('✓ Successfully generated industry rankings!'))
            self.stdout.write(self.style.SUCCESS('Visit http://127.0.0.1:8000/industry-index/ to see the results'))
        else:
            self.stdout.write(self.style.ERROR('✗ Failed to generate rankings. Please check your API key and try again.'))
