# Generated by Django 4.2.7 on 2025-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BS", "Bachelor of Science"),
                            ("MS", "Master of Science"),
                            ("PHD", "Doctor of Philosophy"),
                            ("MBA", "Master of Business Administration"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently enrolled",
                        null=True,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="education/"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of display (lower numbers first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if current position",
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Key achievements (one per line)"
                    ),
                ),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="experience/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., PhD Student, Research Scientist",
                        max_length=200,
                    ),
                ),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
                ("orcid_url", models.URLField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("cv_file", models.FileField(blank=True, null=True, upload_to="cv/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "research_type",
                    models.CharField(
                        choices=[
                            ("PUBLICATION", "Publication"),
                            ("PROJECT", "Research Project"),
                            ("PATENT", "Patent"),
                            ("CONFERENCE", "Conference Paper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "authors",
                    models.CharField(
                        help_text="Comma-separated list of authors", max_length=500
                    ),
                ),
                ("abstract", models.TextField()),
                (
                    "publication_venue",
                    models.CharField(
                        blank=True,
                        help_text="Journal, Conference, etc.",
                        max_length=300,
                    ),
                ),
                ("publication_date", models.DateField()),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="Link to paper/project")),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="research/pdfs/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="research/thumbnails/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=300
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Research",
                "verbose_name_plural": "Research",
                "ordering": ["-publication_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING", "Programming Languages"),
                            ("FRAMEWORK", "Frameworks & Libraries"),
                            ("TOOL", "Tools & Technologies"),
                            ("DATABASE", "Databases"),
                            ("SOFT", "Soft Skills"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        default=50, help_text="Proficiency level (0-100)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
    ]
