# Generated by Django 4.2.7 on 2025-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "Bachelor of Science"),
                    ("BA", "Bachelor of Arts"),
                    ("MS", "Master of Science"),
                    ("MA", "Master of Arts"),
                    ("PHD", "Doctor of Philosophy"),
                    ("MBA", "Master of Business Administration"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="research",
            name="abstract",
            field=models.TextField(
                blank=True, help_text="Research abstract or description"
            ),
        ),
        migrations.AlterField(
            model_name="research",
            name="publication_date",
            field=models.DateField(blank=True, help_text="Publication date", null=True),
        ),
    ]
