# Generated by Django 4.2.7 on 2025-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_education_degree_alter_research_abstract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("HARD", "Hard Skills"),
                    ("SOFT", "Soft Skills"),
                    ("HOBBIES", "Hobbies"),
                ],
                max_length=20,
            ),
        ),
    ]
