# Generated by Django 4.2.7 on 2025-11-01 20:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_alter_skill_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Welcome to My Portfolio", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(default="Professional Title", max_length=300),
                ),
                (
                    "hero_description",
                    tinymce.models.HTMLField(
                        help_text="Main description on hero section"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero section image",
                        null=True,
                        upload_to="landing/",
                    ),
                ),
                (
                    "primary_button_text",
                    models.CharField(default="Download CV", max_length=50),
                ),
                (
                    "primary_button_url",
                    models.CharField(default="/cv/", max_length=200),
                ),
                (
                    "secondary_button_text",
                    models.CharField(default="View Skills", max_length=50),
                ),
                (
                    "secondary_button_url",
                    models.CharField(default="/skills/", max_length=200),
                ),
                ("about_title", models.CharField(default="About Me", max_length=200)),
                (
                    "about_content",
                    tinymce.models.HTMLField(help_text="About section content"),
                ),
                (
                    "show_skills",
                    models.BooleanField(
                        default=True, help_text="Show skills section on homepage"
                    ),
                ),
                (
                    "show_education",
                    models.BooleanField(
                        default=True, help_text="Show education section on homepage"
                    ),
                ),
                (
                    "show_research",
                    models.BooleanField(
                        default=True, help_text="Show research section on homepage"
                    ),
                ),
                (
                    "show_experience",
                    models.BooleanField(
                        default=True, help_text="Show experience section on homepage"
                    ),
                ),
                (
                    "show_blog",
                    models.BooleanField(
                        default=True, help_text="Show blog posts section on homepage"
                    ),
                ),
                (
                    "show_github",
                    models.BooleanField(
                        default=True, help_text="Show GitHub repos section on homepage"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="Page title for SEO", max_length=200
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="Meta description for SEO"),
                ),
            ],
            options={
                "verbose_name": "Landing Page Content",
                "verbose_name_plural": "Landing Page Content",
            },
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Menu item name", max_length=100)),
                (
                    "url",
                    models.CharField(
                        help_text="URL or path (e.g., /skills/ or https://...)",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., fas fa-home)",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show this menu item"),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, help_text="Open link in new tab"
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu Item",
                "verbose_name_plural": "Navigation Menu Items",
                "ordering": ["order"],
            },
        ),
    ]
