# Generated by Django 4.2.7 on 2025-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_landingpagecontent_navigationmenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Welcome to My Portfolio", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(default="Professional Title", max_length=300),
                ),
                (
                    "hero_description",
                    models.TextField(default="Brief introduction about yourself"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
                (
                    "cta_primary_text",
                    models.CharField(default="Download CV", max_length=50),
                ),
                ("cta_primary_url", models.CharField(default="/cv/", max_length=200)),
                (
                    "cta_secondary_text",
                    models.CharField(default="View Skills", max_length=50),
                ),
                (
                    "cta_secondary_url",
                    models.CharField(default="/skills/", max_length=200),
                ),
                ("about_title", models.CharField(default="About Me", max_length=100)),
                ("about_content", models.TextField(blank=True)),
                ("show_stats", models.BooleanField(default=True)),
                (
                    "stat1_number",
                    models.CharField(blank=True, default="5+", max_length=20),
                ),
                (
                    "stat1_label",
                    models.CharField(
                        blank=True, default="Years Experience", max_length=50
                    ),
                ),
                (
                    "stat2_number",
                    models.CharField(blank=True, default="10+", max_length=20),
                ),
                (
                    "stat2_label",
                    models.CharField(blank=True, default="Projects", max_length=50),
                ),
                (
                    "stat3_number",
                    models.CharField(blank=True, default="20+", max_length=20),
                ),
                (
                    "stat3_label",
                    models.CharField(blank=True, default="Skills", max_length=50),
                ),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "show_recent_blog",
                    models.BooleanField(
                        default=True, help_text="Show recent blog posts section"
                    ),
                ),
                (
                    "show_featured_repos",
                    models.BooleanField(
                        default=True, help_text="Show featured GitHub repositories"
                    ),
                ),
                (
                    "show_skills",
                    models.BooleanField(default=True, help_text="Show skills section"),
                ),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
            },
        ),
        migrations.DeleteModel(
            name="LandingPageContent",
        ),
        migrations.DeleteModel(
            name="NavigationMenu",
        ),
    ]
