# Generated by Django 4.2.7 on 2025-11-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_homepage_delete_landingpagecontent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_subtitle",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_description",
            field=models.TextField(
                default="Research Assistant at New York University Abu Dhabi, MSc student at Georgia Institute of Technology",
                help_text="Your professional title and brief introduction",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Your Name", help_text="Your full name", max_length=200
            ),
        ),
    ]
