# Generated by Django 4.2.7 on 2025-11-02 05:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_remove_homepage_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_description",
            field=tinymce.models.HTMLField(
                default="Research Assistant at New York University Abu Dhabi, MSc student at Georgia Institute of Technology",
                help_text="Your professional title and brief introduction - supports rich text formatting",
            ),
        ),
    ]
