# Generated by Django 4.2.7 on 2025-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_homepage_hero_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="cta_secondary_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="cta_secondary_url",
        ),
        migrations.AddField(
            model_name="homepage",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV (PDF format)",
                null=True,
                upload_to="cv/",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_primary_text",
            field=models.CharField(default="View CV", max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_primary_url",
            field=models.CharField(default="#cv-viewer", max_length=200),
        ),
    ]
