# Generated by Django 4.2.7 on 2025-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_remove_homepage_cta_secondary_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="cta_primary_url",
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_primary_text",
            field=models.CharField(
                default="View CV", help_text="Text for the CV button", max_length=50
            ),
        ),
    ]
