# Generated by Django 4.2.7 on 2025-11-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_remove_homepage_cta_primary_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("MICROECONOMICS", "Microeconomics"),
                    ("MACROECONOMICS", "Macroeconomics"),
                    ("SPATIAL_ECONOMICS", "Spatial Economics"),
                    ("ECONOMETRICS", "Econometrics"),
                    ("PROGRAMMING", "Programming & Tools"),
                    ("AI_ML", "AI & Machine Learning"),
                    ("DATA_ANALYSIS", "Data Analysis"),
                    ("GIS", "GIS & Mapping"),
                    ("COMMUNICATION", "Communication"),
                    ("LEADERSHIP", "Leadership"),
                    ("CREATIVE", "Creative"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Skill subcategory for filtering",
                max_length=30,
            ),
        ),
    ]
