# Generated by Django 4.2.7 on 2025-11-03 07:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_skill_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("PAST", "My Past"),
                            ("PRESENT", "My Present"),
                            ("FUTURE", "My Future (Aspirations)"),
                        ],
                        help_text="Which main section this entry belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Year for this timeline entry (e.g., 2013, 2022, 2030)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for this period (e.g., 'Me as a Kid', 'Me in 2022')",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        help_text="Content describing this period of your life - supports rich text formatting"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for this period",
                        null=True,
                        upload_to="timeline/",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order within the period (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show/hide this entry"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timeline Entry",
                "verbose_name_plural": "Timeline Entries",
                "ordering": ["period", "year", "order"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="short_bio",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Short bio for About page (appears before timeline)",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(help_text="Main bio/introduction"),
        ),
    ]
