# Generated by Django 4.2.7 on 2025-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_timelineentry_profile_short_bio_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="year",
            field=models.IntegerField(
                blank=True,
                help_text="Year for this timeline entry (e.g., 2013, 2022, 2030) - Optional",
                null=True,
            ),
        ),
    ]
