# Generated by Django 4.2.7 on 2025-11-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_alter_timelineentry_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title for this period (e.g., 'Me as a Kid', 'Me in 2022') - Optional",
                max_length=200,
            ),
        ),
    ]
