# Generated by Django 4.2.7 on 2025-11-03 08:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0013_alter_timelineentry_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="Research & Publications",
                        help_text="Main title for the research page",
                        max_length=200,
                    ),
                ),
                (
                    "page_description",
                    tinymce.models.HTMLField(
                        default="Explore my research contributions, publications, and academic work.",
                        help_text="Description/bio that appears below the title - supports rich text formatting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research Page Settings",
                "verbose_name_plural": "Research Page Settings",
            },
        ),
    ]
