# Generated by Django 4.2.7 on 2025-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0014_researchpagesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchpagesettings",
            name="all_research_heading",
            field=models.CharField(
                default="All Publications",
                help_text="Heading for the all research section (e.g., 'All Publications', 'Working Papers', 'Research Projects')",
                max_length=100,
            ),
        ),
    ]
