# Generated by Django 4.2.7 on 2025-11-03 09:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0015_researchpagesettings_all_research_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro_bio",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Introduction bio that appears at the top of the About page, before the timeline - supports rich text formatting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page Settings",
                "verbose_name_plural": "About Page Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="timelineentry",
            options={
                "ordering": ["period", "year", "order"],
                "verbose_name": "About Me - Timeline Entry",
                "verbose_name_plural": "About Me",
            },
        ),
    ]
