# Generated by Django 4.2.7 on 2025-11-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0016_aboutpagesettings_alter_timelineentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagesettings",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV (PDF format)",
                null=True,
                upload_to="cv/",
            ),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="google_scholar_url",
            field=models.URLField(blank=True, help_text="Google Scholar profile URL"),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="orcid_url",
            field=models.URLField(blank=True, help_text="ORCID profile URL"),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Your profile photo",
                null=True,
                upload_to="profile/",
            ),
        ),
        migrations.AddField(
            model_name="aboutpagesettings",
            name="twitter_url",
            field=models.URLField(blank=True, help_text="Twitter/X profile URL"),
        ),
    ]
