# Generated by Django 4.2.7 on 2025-11-03 09:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0017_aboutpagesettings_cv_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryIndexSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_description",
                    tinymce.models.HTMLField(
                        default="This ranking is generated by AI analyzing my skills, research interests, blog posts, education, and professional activities. The index updates regularly to reflect my evolving expertise and interests.",
                        help_text="Description explaining how the industry ranking works",
                    ),
                ),
                (
                    "current_industry",
                    models.CharField(
                        blank=True,
                        help_text="Your current industry (e.g., 'Technology', 'Finance', 'Healthcare'). Leave blank to auto-detect from homepage.",
                        max_length=200,
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI API key for generating industry rankings",
                        max_length=500,
                    ),
                ),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time rankings were generated",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry Index Settings",
                "verbose_name_plural": "Industry Index Settings",
            },
        ),
        migrations.CreateModel(
            name="IndustryRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry_name",
                    models.CharField(help_text="Name of the industry", max_length=200),
                ),
                (
                    "rank",
                    models.IntegerField(
                        help_text="Ranking position (1 = most relevant)"
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(help_text="Relevance score (0-100)"),
                ),
                (
                    "reasoning",
                    models.TextField(
                        help_text="AI-generated explanation for this ranking"
                    ),
                ),
                (
                    "key_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of relevant skills"
                    ),
                ),
                (
                    "is_current_industry",
                    models.BooleanField(
                        default=False, help_text="Is this your current industry?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show/hide this ranking"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry Ranking",
                "verbose_name_plural": "Industry Rankings",
                "ordering": ["rank"],
            },
        ),
    ]
